### ISSUE TITLE
Https:// errors

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SparrowTennessee#106]
![image](https://cloud.githubusercontent.com/assets/12058013/24210229/d04ab8cc-0efe-11e7-937a-b7b06c2503de.png)

**Comment by HansVraga** [comment]
Down to one error:

![image](https://cloud.githubusercontent.com/assets/12058013/24311152/429abeb2-10a9-11e7-9d48-3e48e8c2450e.png)

**Comment by esmyers** [comment]
I think this is ok.  Network issues making testing hard, but will confirm off-network tomorrow.
