### ISSUE TITLE
Region multi-select (to build graphs/table)

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SparrowTennessee#113]
You can currently zoom a section of the graph to see a subset of the geographies (highlighted when you do so). We want to enable the user to get this another way - selecting a set of geographies to show as a graph.

The tool should work very similar to the WLERA tool for selecting parcels: either the user enters "select' mode and clicks on each geography individually to select them, then requests the graph of their selection. Or they draw a box which selects all geographies that intersect with the box and displays a graph.

**Comment by troddick** [comment]
moved to sparrow-mrb3-js repo
