### ISSUE TITLE
Fix strange characters in About Modal

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SparrowTennessee#119]
Strange characters in the below About Modal tabs need to be replaced with appropriate text. 

- [ ] Model Documentation

- [ ] Data Limitations

- [x] Definitions

**Comment by HansVraga** [comment]
(Screenshot for example)

![image](https://cloud.githubusercontent.com/assets/12058013/24628711/7b3bdd30-1885-11e7-9fe7-1c41cf0ab1fb.png)

**Comment by HansVraga** [comment]
Checked Definitions - needs changes as per #121

**Comment by esmyers** [comment]
I don't see special characters in chrome.  These look like a problem with the quotation marks though.  Is this still happening?

**Comment by esmyers** [comment]
..and in what browser?

**Comment by HansVraga** [comment]
Chrome - here is another screenshot with URL: (maybe this isn't most up-to-date?):
![image](https://cloud.githubusercontent.com/assets/12058013/25026829/7dbb5bc8-2076-11e7-9545-f6ca082643ea.png)

**Comment by esmyers** [comment]
<meta charset="utf-8">
