### ISSUE TITLE
Update About -> Definitions

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SparrowTennessee#121]
Replace current content of About -> Definitions with the following text:

**Load from** (areal unit such as HUC8, HUC10, Independent Watershed, or State, or fragment of State that overlaps with the other three units)  **delivered to** (target point on the stream network such as downstream model boundary, HUC8 outlet, HUC10 outlet)  **(lb/yr)**:   The predicted mean annual load of the constituent that originates within the areal unit and reaches the target point and thus is not attenuated or removed by natural processes during stream transport. 
 
**Yield from** (areal unit such as HUC8, HUC10, Independent Watershed, or State, or fragment of State that overlaps with the other three units)  **delivered to** (target point such as downstream model boundary, HUC8 outlet, HUC10 outlet) **(lb/yr/acre)**:  The load (as defined above) divided by the area of the areal unit.
 
**Accumulated load at HUC10 outlet (lb/yr)**:   The predicted mean annual load of the constituent at the outlet of the HUC10 that reflects the accumulated mass of the constituent contributed by all sources in the total drainage area upstream of the outlet (including all HUC10s upstream from this HUC10, if any). The accumulated load value includes the effects of in-stream attenuation processes in all upstream reaches.
 
**Accumulated yield at HUC10 outlet (lb/yr/acre)**:  The Accumulated Load at HUC10 outlet divided by the total drainage area upstream of the HUC10 outlet.

**Load from** (areal unit defined by fragment of State within the model area, or the fragment of State within a HUC10, HUC8, or Independent Watershed) **within model area, lb/yr**:   The sum of predicted mean annual load of the constituent from all model catchments that lie within the areal unit and also that lie within the model area boundary.  The summed catchment values are the incremental load for the catchment, and includes the effects of in-stream attenuation processes associated with one half of the incremental reach length.

**Yield from** (areal unit defined by fragment of State within the model area, or the fragment of State within a HUC10, HUC8, or Independent Watershed) **within model area, lb/yr/acre**:  The load (as defined above) divided by the area of the areal unit. 
 
**Independent Watersheds** are the large (in most cases) subwatersheds that comprise the Tennessee model area.  With one exception (the “smaller tributaries to the Mississippi River”), the Independent Watersheds are delineated as the upstream drainage for each of the flow paths that exit the Tennessee SPARROW model area.  The Watershed “smaller tributaries to the Mississippi River” does not have a single exit point; rather, multiple exit points where each tributary to the Mississippi River in West Tennessee discharges to the Mississippi River.

**The downstream model boundary** is the point where the flow path exits the Tennessee SPARROW model area boundary.

- For the Cumberland River and Tennessee River Basins this point is the confluence of the Cumberland River or Tennessee River, respectively, with the Ohio River.
- For the Conasauga River basin it is the confluence of the Conasauga River with the Oostanaula River.
- For the Barren River basin it is the confluence of the Barren River with the Green River.
- For the Yellow River diversion to the Tombigbee River it is the point where the Tennessee-Tombigbee canal enters the Mackeys Creek watershed.
- For the smaller tributaries to the Mississippi River it is the multiple points where the tributaries discharge to the Mississippi River.

**Comment by esmyers** [comment]
Is this the most current text?  I will replace and update ASAP on confirmation.

**Comment by HansVraga** [comment]
I think the answer is yes. This is the last text I've seen from Ann, Dale, or Dave.
