### ISSUE TITLE
Change layout/default of yield/load buttons

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SparrowTennessee#20]
From Ann:
>1.   We all agreed that yield is more useful than load when making comparisons across a map or across a series of barcharts,   so we wondered if Yield could be listed before Load in the "Displayed Metric"  box,  and, more importantly,  if Yield could be the default that the map goes to when launching,  or when switching anything (e.g. switching between models,  or switching  Group Results , etc.)

**Comment by troddick** [comment]
switch [1] to [0] in config to get yield first.

**Comment by troddick** [comment]
Done
