### ISSUE TITLE
table hide() and hide button

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/SparrowTennessee#23]
will also need to call the hide() on if (Group Results != HUC10)

**Comment by esmyers** [comment]
Will also need to hide the chart if they change nutrient model Radio Button.
couple of options here:

1.  show the table automatically on Radio Change, loading new data **(preferred)**
2. close chart and make user reload manually.

**Comment by troddick** [comment]
I'll work on this this morning

**Comment by troddick** [comment]
updated in Tdev. 
- added close table x to table (maybe css or different location than pulled left of table title?)
- when group results by is changed from huc10, table goes away
- when radio button changed, if table is visible, refreshes content

Should we leave these open until merged into master or close as we finish on our branch??

**Comment by troddick** [comment]
updated in master
