### ISSUE TITLE
Aggregate/AOI checks to inhibit impossible combinations

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/SparrowTennessee#26]

**Comment by esmyers** [comment]
Some query combos just don't work when AOIs are selected.  Need to check for those and disable accordingly

**Comment by troddick** [comment]
(top down)
If **Area of Interest** choices contain:
Independent Watershed & HUC8 ==> 
then Group Results By choice is Independent Wathershed ==>
clear HUC8 chosen in Area of Interest

If **Area of Interest** choices contain:
Independent Watershed & HUC8 ==>
then Group Results by choice is State ==>
clear both Independent Watershed and HUC8 in Area of Interest

(bottom up)
If **Group Results By** choice is:
Independent Watershed ==> disable HUC8 in Area of Interest
State ==> disable Independent Watershed and HUC8 in Area of Interest

can add something to the AOI Change event function.

**Comment by troddick** [comment]
Done
