### ISSUE TITLE
Table and State AOI bug

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/SparrowTennessee#28]
Table needs to draw from GRP_3_ST in Sparrow-config.js when ST AOI is selected.  These are different layers and won't return the same data.

**Comment by troddick** [comment]
add check for group_3_st doesn't have duplate 'ST_GP3_NAM' when building header and body

**Comment by esmyers** [comment]
This got very complex and we decided to dump all attributes in the services into the table.
