### ISSUE TITLE
Reset Chart Zoom to Default

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/SparrowTennessee#34]
We may or may not need to do this depending on how we implement the infoWindow single bar chart to full extent and back.

**Comment by esmyers** [comment]
To clarify, after dragging to select specific bars in the chart, there is a reset button that can be used to go back to default.  I already have the reset working, it's the button display in the lobipanel that is giving me grief.  Have left the reset button commented out for the time being.

**Comment by troddick** [comment]
reset zoom button fixed.
