### ISSUE TITLE
Legend CSS cleanup

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/SparrowTennessee#38]
1. number format the legend classes to 2 decimals
2. dynamically add the correct layer and displayed metric to the legend heading.
3. work on display css for the legend widget as the sizing gets funky refreshing legend with the div open.

**Comment by troddick** [comment]
1. done.

**Comment by troddick** [comment]
2. Erik
3. Mitch

**Comment by esmyers** [comment]
2. Done
