### ISSUE TITLE
radio buttons for Phosphorus and Nitrogen not consistently working

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SparrowTennessee#40]
Sometimes the click selects the radio option and sometimes it doesn't.

**Comment by troddick** [comment]
Will start out by changing from name="radio1" to name="nutrientRadio" for both and then making Phosporus selected via jquery onLoad rather than in the html.

**Comment by troddick** [comment]
sporadic. Haven't had an issue with this all day today.

**Comment by HansVraga** [comment]
Closing - this seems to work fine for me.
