### ISSUE TITLE
UI work on InfoWindow Chart buttons

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/SparrowTennessee#43]
need to add the Show Full chart button to the single bar chart.   

1. After the user clicks on a bar in the full chart
2. After the user clicks on the show chart button from the InfoWindow

**Comment by troddick** [comment]
Show full chart button added to single bar chart window. Full bar chart has reset zoom button back. 
Need to add feature properties to initial feature click popup with 'Show Chart' button below to show single bar chart.

**Comment by esmyers** [comment]
All that is left is @ #44
