### ISSUE TITLE
Way to keep version up-to-date via Gulp

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SparrowTennessee#50]
Similar to Streamstats (screenshot below)
Add the version number of the application to the About title after "SPARROW Tennessee";

![image](https://cloud.githubusercontent.com/assets/12058013/23443063/5f5d34a6-fdfa-11e6-8521-3d6ab9f91e9d.png)

**Comment by troddick** [comment]
Where would you like this to go?

![image](https://cloud.githubusercontent.com/assets/1580076/23462082/119273aa-fe52-11e6-8756-a87fcd40f2bb.png)

Also, what version number should I put?

**Comment by HansVraga** [comment]
Same place, format as the streamstats screenshot will do - after the title. 
I suppose you could start with 0.9.0 until you guys are ready  for 1.0.0

**Comment by troddick** [comment]
Added it via html. Need a way to auto update via gulp.

**Comment by troddick** [comment]
moved to sparrow-mrb3-js repo
