### ISSUE TITLE
Geosearch - add text/enable search by HUC, USGS sites

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SparrowTennessee#57]
Two items pertaining to the Geosearch, which is using the USGS Search JS API:

- [x] Turn on the ability to search by HUC codes and USGS sites

- [x] Update the Modal to include the text in this screenshot: 
(found by visiting test.wim.usgs.gov/streamstats/ and clicking on the "?" next to the "search" bar in the upper-left

![image](https://cloud.githubusercontent.com/assets/12058013/23624530/fe05d9e6-0273-11e7-87dc-a990118cbfcd.png)

**Comment by HansVraga** [comment]
It appears second item (described above) not complete? Checked first item.

**Comment by esmyers** [comment]
Left area codes out since I don't have them enabled.
