### ISSUE TITLE
GeoSearch zoom level

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SparrowTennessee#58]
When Map zooms/pans to search point, do not allow Zoom past level 12.

**Comment by HansVraga** [comment]
Also, when possible, make use of the extent the API passes back over the point.

**Comment by esmyers** [comment]
set custom scale ranges in the app.map constructor 
ref: https://geonet.esri.com/thread/61462

**Comment by HansVraga** [comment]
@esmyers - donno if this matters (close this issue again if you don't think so) but Nick just implemented a method that uses extent when it matters, and stops zoom at 12 if it's a point...


https://github.com/USGS-WiM/fim-js/blob/staging/src/scripts/core.js#L793-L819

**Comment by esmyers** [comment]
Like it. Switched to that.
