### ISSUE TITLE
Allow for clicking and loading a particular bar

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SparrowTennessee#6]
If a user highlights a bar, give an option to load that bar

**Comment by esmyers** [comment]
Need to figure out how to pass the feature from app.executeIdentifyTask()  to app.createChartQuery() as the whereClause.  Will need to think about that because the chart query is set up to fire without passing in an argument.

**Comment by esmyers** [comment]
Closing this issue since the major work is done.  Now moving the remaining tasks to #43  which is UI work.
