### ISSUE TITLE
View Table based on Data in Chart

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SparrowTennessee#61]
Add ability to view a table populated with Data making up the chart. Add this option for a single chart, full chart, or any zoomed chart.

Consider showing this in the bottom panel. As the Chart dynamically changes based on selections, have the table change with the chart.

**Comment by esmyers** [comment]
Was the request to view the chart data as a table, or was it to export it to a tabular format like CSV?  I thought the latter and was working on a .CSV export

**Comment by HansVraga** [comment]
If we make any chart view-able as a table, this means that for single polygons / cachements we'll have the tabular information ready. 

And you could export from that table view. 

In my mind, this ties together all the facets. Right now the Table is disconnected.

**Comment by troddick** [comment]
moved to sparrow-mrb3-js repo
