### ISSUE TITLE
About Tab -> About the Application

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SparrowTennessee#87]
Change this tab title to "Model Documentation" 
Populate with below text:
<normal>
SPARROW Surface Water-Quality Modeling https://water.usgs.gov/nawqa/sparrow/
<sub-heading>
“Documentation of the SPARROW model for Tennessee”  
<normal>
Hoos, A.B., and Wang, S., 2017, Adapting a regional water-quality model for a statewide watershed management application – example for the southeastern U.S.: Journal of xxxxx

<sub-heading>
“Documentation of the modeling tool SPARROW (SPAtially Referenced Regression On Watershed attributes)”  
<normal>
* Schwarz, G.E., A.B. Hoos, R.B. Alexander, and R.A. Smith, 2006. The SPARROW Surface Water-Quality Model: Theory, Application, and User Documentation. U.S. Geological Survey Techniques and Methods Report, Book 6, Chapter B3.  https://pubs.usgs.gov/tm/2006/tm6b3/ ;
* Preston, S.D., Alexander, R.B., Woodside, M.D., and Hamilton, P.A., 2009, SPARROW MODELING—Enhancing Understanding of the Nation’s Water Quality: U.S. Geological Survey Fact Sheet 2009–3019, 6 p. https://pubs.usgs.gov/fs/2009/3019/

**Comment by HansVraga** [comment]
Need Tab title Updated.

**Comment by esmyers** [comment]
fixed at #97.  Also changed the glyphicons to more sensicaal symbols
